# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @keywords internal
#' @noRd
#' 
NULL

getneighbor_weightmat <- function(x, radius, width) {
    .Call(`_SpaCOAP_getneighbor_weightmat`, x, radius, width)
}

spacoap_cpp <- function(X_count, a, Z, H, Adj_sp, rank_use, Mu_y_int, S_y_int, invLambda_int, B_int, alpha_int, bbeta_int, M_int, S_int, epsELBO, maxIter, verbose, up_eta, w_plus_vec, wt_sq_sum, algo, fast_svd = TRUE, add_IC_inter = FALSE) {
    .Call(`_SpaCOAP_spacoap_cpp`, X_count, a, Z, H, Adj_sp, rank_use, Mu_y_int, S_y_int, invLambda_int, B_int, alpha_int, bbeta_int, M_int, S_int, epsELBO, maxIter, verbose, up_eta, w_plus_vec, wt_sq_sum, algo, fast_svd, add_IC_inter)
}

